"""new models for generation runs etc

Revision ID: 002_new_models_for_generation_runs
Revises: 001_initial_setup
Create Date: 2026-04-03 16:44:36.008103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '002_new_models_for_generation_runs'
down_revision: Union[str, Sequence[str], None] = '001_initial_setup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methodologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_methodologies_id'), 'methodologies', ['id'], unique=False)
    op.create_table('service_line_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_service_line_categories_id'), 'service_line_categories', ['id'], unique=False)
    op.create_table('service_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_line_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_service_lines_id'), 'service_lines', ['id'], unique=False)
    op.create_table('generation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sow_id', sa.Integer(), nullable=False),
    sa.Column('methodology', sa.String(length=50), nullable=False),
    sa.Column('service_line_codes', sa.JSON(), nullable=False),
    sa.Column('artifact_types_requested', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True, comment='pending -> extracting_modules -> generating_artifacts -> completed -> failed'),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_id'), 'generation_runs', ['id'], unique=False)
    op.create_table('project_service_lines',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('service_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['service_line_id'], ['service_lines.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'service_line_id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('methodology_format', sa.String(length=50), nullable=True),
    sa.Column('parent_artifact_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_section_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.add_column('modules', sa.Column('generation_run_id', sa.Integer(), nullable=False))
    op.add_column('modules', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('modules', sa.Column('source_section_ids', sa.JSON(), nullable=True))
    op.add_column('modules', sa.Column('module_order', sa.Integer(), nullable=True))
    op.alter_column('modules', 'name',
               existing_type=mysql.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('modules_ibfk_1'), 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'generation_runs', ['generation_run_id'], ['id'])
    op.drop_column('modules', 'status')
    op.drop_column('modules', 'updated_at')
    op.drop_column('modules', 'project_id')
    op.drop_column('modules', 'progress')
    op.drop_column('modules', 'created_at')
    op.add_column('projects', sa.Column('methodology_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'methodology_code')
    op.add_column('modules', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.add_column('modules', sa.Column('progress', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('modules', sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('modules', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.add_column('modules', sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.create_foreign_key(op.f('modules_ibfk_1'), 'modules', 'projects', ['project_id'], ['id'])
    op.alter_column('modules', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=225),
               existing_nullable=False)
    op.drop_column('modules', 'module_order')
    op.drop_column('modules', 'source_section_ids')
    op.drop_column('modules', 'description')
    op.drop_column('modules', 'generation_run_id')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('project_service_lines')
    op.drop_index(op.f('ix_generation_runs_id'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_index(op.f('ix_service_lines_id'), table_name='service_lines')
    op.drop_table('service_lines')
    op.drop_index(op.f('ix_service_line_categories_id'), table_name='service_line_categories')
    op.drop_table('service_line_categories')
    op.drop_index(op.f('ix_methodologies_id'), table_name='methodologies')
    op.drop_table('methodologies')
    # ### end Alembic commands ###
