"""add project_type to projects

Revision ID: 012_add_project_type_to_projects
Revises: 011_add_design_runs_and_design_artifacts
Create Date: 2026-05-01 15:34:03.070933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012_add_project_type_to_projects'
down_revision: Union[str, Sequence[str], None] = '011_add_design_runs_and_design_artifacts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
