"""add design_runs and design_artifacts

Revision ID: ad00d2fcc174
Revises: 010_seed_config_yamls
Create Date: 2026-04-27 14:15:11.300255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad00d2fcc174'
down_revision: Union[str, Sequence[str], None] = '010_seed_config_yamls'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sow_id', sa.Integer(), nullable=True),
    sa.Column('generation_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True, comment='pending → generating → completed → failed'),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_runs_id'), 'design_runs', ['id'], unique=False)
    op.create_table('design_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_run_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['design_run_id'], ['design_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_artifacts_id'), 'design_artifacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_artifacts_id'), table_name='design_artifacts')
    op.drop_table('design_artifacts')
    op.drop_index(op.f('ix_design_runs_id'), table_name='design_runs')
    op.drop_table('design_runs')
    # ### end Alembic commands ###
