import enum
from sqlalchemy import Column, Integer, Text, String, ForeignKey, JSON, DateTime, func
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import relationship
from app.db.database import Base

class ArtifactVersionSource(str, enum.Enum):
    """
    Tracks how each version of an artifact was produced.
    This lets us show users a clear audit trail:
    "Generated by AI → Refined by AI with your feedback → Edited manually"
    """
    GENERATED = "generated" # produced by the initial bulk generation pipeline
    REFINED = "refined"     # produced by a targeted LLM refinement call
    MANUAL = "manual"       # produced by a user typing directly in the editor

class ArtifactVersion(Base):
    __tablename__ = "artifact_versions"
    id = Column(Integer, primary_key=True, index=True)

    # Which artifact this version belongs to.
    # ondelete=CASCADE means if an artifact is deleted, all its versions go with it.
    artifact_id = Column(
        Integer, 
        ForeignKey("artifacts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    version_number = Column(Integer, nullable=False)
    content_json = Column(JSON, nullable=False)
    content_markdown = Column(Text, nullable=True)
    refinement_feedback = Column(Text, nullable=True)
    source = Column(SAEnum(ArtifactVersionSource, 
                    values_callable=lambda obj: [e.value for e in obj]),
                    nullable=False)
    llm_metadata = Column(JSON, nullable=True)
    created_at = Column(DateTime, server_default=func.now())

    artifact = relationship(
        "Artifact",
        foreign_keys=[artifact_id],
        back_populates="versions",
    )